# Generated by Django 3.1.7 on 2021-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
