# Generated by Django 3.1.7 on 2021-03-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='ranking',
            new_name='globalranking',
        ),
        migrations.AddField(
            model_name='rank',
            name='collegeRanking',
            field=models.IntegerField(default=0),
        ),
    ]
