# Generated by Django 3.1.7 on 2021-03-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210328_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='globalranking',
            new_name='countryranking',
        ),
    ]
