# Generated by Django 3.1.7 on 2021-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210328_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='globalranking',
            field=models.IntegerField(default=0),
        ),
    ]
