# Generated by Django 3.1.7 on 2021-04-01 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rank_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='pastcontest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pastrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_rank', models.IntegerField()),
                ('college_contest_rank', models.IntegerField()),
                ('totalScore', models.IntegerField()),
                ('pastcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pastcontest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rank')),
            ],
        ),
    ]
