# Generated by Django 3.1.7 on 2021-04-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pastcontest_pastrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastrank',
            name='college_contest_rank',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='collegeRanking',
        ),
    ]
