# Generated by Django 3.1.7 on 2021-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210401_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastcontest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
