# Generated by Django 3.1.7 on 2021-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210401_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastrank',
            name='totalScore',
            field=models.FloatField(),
        ),
    ]
