# Generated by Django 3.1.7 on 2021-04-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210401_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='collegerank',
            field=models.IntegerField(default=0),
        ),
    ]
